notepad/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from notes.views import note_list_view, finish_item, delete_item, recover_item

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', note_list_view, name='note-list'),
    path('finish-item/<id>/', finish_item, name='finish-note-item'),
    path('recover-item/<id>/', recover_item, name='recover-note-item'),
    path('delete-item/<id>/', delete_item, name='delete-note-item')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes/models.py
from django.db import models
from django.shortcuts import redirect, reverse

LABEL_CHOICES = (
    ('WARNING', 'warning'),
    ('PRIMARY', 'primary'),
    ('SECONDARY', 'secondary')
)

class Note(models.Model):
    title = models.CharField(max_length=100)
    due_date = models.DateField()
    label = models.CharField(choices=LABEL_CHOICES, max_length=9)
    finished = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def get_finish_item_url(self):
        return reverse("finish-note-item", kwargs={
            'id': self.id
        })

    def get_recover_item_url(self):
        return reverse("recover-note-item", kwargs={
            'id': self.id
        })

    def get_delete_item_url(self):
        return reverse("delete-note-item", kwargs={
            'id': self.id
        })

notes/forms.py
from django import forms
from .models import Note


class DateInput(forms.DateInput):
    input_type = 'date'


class NoteModelForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ('title', 'due_date', 'label')
        widgets = {
            'due_date': DateInput(),
        }

notes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Note
from .forms import NoteModelForm


def note_list_view(request):
    form = NoteModelForm()
    if request.method == "POST":
        form = NoteModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("note-list")
    to_do_list = Note.objects.filter(finished=False)
    finished_list = Note.objects.filter(finished=True)
    context = {
        'to_do_list': to_do_list,
        'finished_list': finished_list,
        'form': form
    }
    return render(request, "note_list.html", context)

def finish_item(request, id):
    note = get_object_or_404(Note, id=id)
    note.finished = True
    note.save()
    return redirect('note-list')

def recover_item(request, id):
    note = get_object_or_404(Note, id=id)
    note.finished = False
    note.save()
    return redirect('note-list')

def delete_item(request, id):
    note = get_object_or_404(Note, id=id)
    note.delete()
    return redirect('note-list')

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Starter Template · Bootstrap</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <a class="navbar-brand" href="">To-Do List Application</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="">Home <span class="sr-only">(current)</span></a>
      </li>

      
    </ul>

  </div>
</nav>

<main role="main" class="container">

{% block content %}

{% endblock content %}

</main><!-- /.container -->

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

templates/note_list.html
{% extends "base.html" %}

{% block content %}

<style>
h3 {
  position: relative;
}

.icons {
  position: absolute;
  right: 5px;
}

</style>

    <div class="text-center mt-5">
      <h1>To-Do Lists
      <a data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
        <i class="fas fa-plus fa-sm"></i>
      </a>
      </h1>
    </div>
    <hr>



    <div class="collapse" id="collapseExample">
      <div class="card card-body">
        <form method="POST">
          {% csrf_token %}
          <div class="form-group">
            <label for="id_title">Title</label>
            {{ form.title }}
          </div>
          <div class="form-group">
            <label for="id_due_date">Due Date</label>
            {{ form.due_date }}
          </div>
          <div class="form-group">
            <label for="id_label">Label</label>
            {{ form.label }}
          </div>
          <button type="submit" class="btn btn-primary">Create</button>
        </form>
      </div>
    </div>





    <div class="row">
      {% for note in to_do_list %}
      <div class="col-12">
      {% include "note_snippet.html" with note_snippet_var=note type="DELETE" %}
      </div>
      {% endfor %}
    </div>

    <div class="text-center mt-5">
      <h1>Finished Lists</h1>
    </div>
    <hr>
    <div class="row">
      {% for note in finished_list %}
      <div class="col-12">
      {% include "note_snippet.html" with note_snippet_var=note type="ADD" %}
      </div>
      {% endfor %}
    </div>
{% endblock content %}

templates/note_snippet.html
<div class="card">
  <div class="card-body">
    <h3>{{ note_snippet_var.title }} <span class="badge badge-{{ note_snippet_var.get_label_display }}">
    {{ note_snippet_var.label }} / Deadline: {{ note_snippet_var.due_date }}
    <span class="icons">
    {% if type == "DELETE" %}
    <a href="{{ note_snippet_var.get_finish_item_url }}"><i class="fas fa-check"></i></a>
    {% else %}
    <a href="{{ note_snippet_var.get_recover_item_url }}"><i class="fas fa-times"></i></a>
    {% endif %}
    <a href="{{ note_snippet_var.get_delete_item_url }}"><i class="fas fa-trash" style="color: red;"></i></a>
    </span>
    </h3>
  </div>
</div>